In [9]:
print('Hello, world!')

Hello, world!


In [15]:
print('wech\ncava?\n')

wech
cava?



In [20]:
print('go'+''+'my'+'code')

gomycode


In [28]:
input('whats your name?')

KeyboardInterrupt: Interrupted by user

In [26]:
input('whats your name?')

whats your name?jhbkjb


'jhbkjb'

In [30]:
print('Day 1 - String Manipulation')
print('String Concatenation is done with the "+" sign.')
print('e.g. print("Hello " + "world")')
print('New lines can be created with a backslash and n.')

Day 1 - String Manipulation
String Concatenation is done with the "+" sign.
e.g. print("Hello " + "world")
New lines can be created with a backslash and n.


In [38]:
num=int(input('Entrez un nombre'))
if num >0:
    print('Ce numero est positif')
else:
    print('ce numero est non positif')

Entrez un nombre0
ce numero est non positif


In [41]:
num=int(input('Entrez un nombre'))
if num>=0:
    print('Ce nombre est positif')
else:
    print('Ce nombre est negatif')

Entrez un nombre-2
Ce nombre est negatif


In [17]:
num=float(input('Entrez la note'))
if num>15:
    print('trés bien')
elif num>13:
    print('bien')
elif num>10:
    print('moyen')
else:
    print('pas bien')

Entrez la note16
trés bien


In [16]:
x=float(input('Renseignez la note'))
y=input('Est t-il insrict a une activité sportive?')

if x>10:
    if y=="oui":
        x=x+1
    print("très bien")
elif x<10 and y=="non":
    print('nul')
elif x<10 and y=="oui":
    x=x+1
    print('nul')
else:
    print('trés bien')
print("la note est:",x)

Renseignez la note16
Est t-il insrict a une activité sportive?oui
très bien
la note est: 17.0


In [43]:
x=float(input('Renseignez la note'))
y=input('Est t-il insrict a une activité sportive?')

if x>10:
    if y=="oui":
        x=x+1
    print("très bien")

Renseignez la note15
Est t-il insrict a une activité sportive?oui
très bien


In [1]:
n=float(input('Rentrez un nombre'))
if n%2==0:
    print("pair")
else:
    print('impair')

Rentrez un nombre3
impair


In [2]:
print(round(8/3))

3


In [ ]:
x=int(input('quel est votre age?'))
y=90-x
z=y*12
s=y*52
d=y*365
print(f"You have {d} days, {s} weeks, and {z} months left")

In [2]:
import numpy as np
x=np.random.randint(0,5)
b=True
while b==True:
    y=int(input('Entrez un nombre entre 0 et 5'))
    if y>x:
        print('Rentrez un nombrez plus petit')
    elif y<x:
        print('Rentrez un nombre plus grand')
    else:
        print('Tres bien')
        b=False

KeyboardInterrupt: Interrupted by user

In [13]:
for i in range(6):
    print(i)


0
1
2
3
4
5


In [16]:
import numpy as np
x=np.random.randint(0,5)
b=True
for i in range(0,3,1):
    y=int(input('Entrez un nombre entre 0 et 5'))
    if y>x:
        print('Rentrez un nombrez plus petit')
    elif y<x:
        print('Rentrez un nombre plus grand')
    else:
        print('Tres bien')
        break

Entrez un nombre entre 0 et 52
Rentrez un nombrez plus petit
Entrez un nombre entre 0 et 52
Rentrez un nombrez plus petit
Entrez un nombre entre 0 et 52
Rentrez un nombrez plus petit


In [21]:
i=0
while i<6:
        print(i)
        i+=1

0
1
2
3
4
5


In [4]:
import numpy as np
x=np.random.randint(0,5)
i=1
b=True
while i<4 and b==True:
    y=int(input('Entrez un nombre entre 0 et 5'))
    if y>x:
        print('Rentrez un nombrez plus petit')
    elif y<x:
        print('Rentrez un nombre plus grand')
    else:
        print('tres bien')
        b=False
    i+=1

Entrez un nombre entre 0 et 52
Rentrez un nombrez plus petit


KeyboardInterrupt: Interrupted by user

In [39]:
import math
print(math.pi)

3.141592653589793


In [9]:
note=[15,14.5,7,19]
note[-2]

7

In [12]:
x=int(input('Rentrez le nombre d"eleves'))
l=[]


for i in range (x):
    if i==0:
        y=float(input(f'Entrez la {i+1}ère note '))
    else:
        y=float(input(f'Entrez la {i+1}ème note '))
    
    l.append(y)
print('la moyenne est',sum(l)/x,'le max est', max(l),'le min est',min(l))

z=int(input('Rentrez le numéro de l"elève'))
n=l[z-1]
if n>12:
    print(f'la note est {y} appreciation bien')
elif n==10:
    print(f'la note est {y} appreciation passable')
elif n<10:
    print(f'la note est {y} appreciation nul')
else:
    print(f'la note est {y} appreciation convenable')


Rentrez le nombre d"eleves5
Entrez la 1ere note 1
Entrez la 2eme note 2
Entrez la 3eme note 3
Entrez la 4eme note 4
Entrez la 5eme note 5
la moyenne est 3.0 le max est 5.0 le min est 1.0
Rentrez le numéro de l"elève3
la note est 5.0 appreciation nul


In [5]:
a=float(input('Rentrez le premier nombre'))
b=input('Rentrez le premier operateur')
if b not in ('+','-','/','*'):
    print('veuillez saisir un operateur')
else:
    c=float(input('Rentrez le deuxieme nombre'))
    while b in ('+','-','/','*'):
        if b=='-':
            print(f'{a}-{c}={a-c}')
            break
        elif b =='/':
            print(f'{a}/{c}={a/c}')
            break
        elif b =='*':
            print(f'{a}*{c}={a*c}')
            break
        else:
            print(f'{a}+{c}={a+c}')
            break

Rentrez le premier nombre15
Rentrez le premier operateur+
Rentrez le deuxieme nombre5
15.0+5.0=20.0


In [10]:
a=float(input('Rentrez le premier nombre'))
b=input('entrez le premier operateur')
while b not in ('+','-','/','*'):
    b=input('Rentrez le premier operateur')
c=float(input('Rentrez le deuxieme nombre'))
if b=='-':
    print(f'{a}-{c}={a-c}')
elif b =='/':
    print(f'{a}/{c}={a/c}')
elif b =='*':
    print(f'{a}*{c}={a*c}')
else:
    print(f'{a}+{c}={a+c}')

Rentrez le premier nombre4
entrez le premier operateur4
Rentrez le premier operateur4
Rentrez le premier operateur4
Rentrez le premier operateur4
Rentrez le premier operateur*
Rentrez le deuxieme nombre2
4.0*2.0=8.0


In [11]:
a=float(input('Rentrez le premier nombre'))
v=True
while v==True:
    b=input('Rentrez le premier operateur')
    if b in ('+','-','/','*'):
        v=False
        
c=float(input('Rentrez le deuxieme nombre'))
if b=='-':
    print(f'{a}-{c}={a-c}')
elif b =='/':
    print(f'{a}/{c}={a/c}')
elif b =='*':
    print(f'{a}*{c}={a*c}')
else:
    print(f'{a}+{c}={a+c}')

Rentrez le premier nombre15
Rentrez le premier operateur2
Rentrez le premier operateur2
Rentrez le premier operateur+
Rentrez le deuxieme nombre5
15.0+5.0=20.0


In [36]:
print('Welcome to Python Pizza Deliveries')
m=20
o=15
l=25
v=True
while v==True:
    s=input('which size you want?')
    if s in ('m','s','l'):
        v=False
x=True
while x==True:
    p=input('Do you want pepperoni?')
    if p in ('y','n'):
        x=False
w=True
while w==True:
    c=input('Do you want extra cheese?')
    if c in ('y','n'):
        w=False
if s=='m':
    if c=='y':
        if p=='y':
            print(f'Your final bill is: {m+1+3}$')
        else:
            print(f'Your final bill is: {m+1}$')
    elif p=='y':
        print(f'Your final bill is: {m+3}$')
    else:
        print(f'Your final bill is: {m}$')
elif s=='s':
    if c=='y':
        if p=='y':
            print(f'Your final bill is: {o+1+2}$')
        else:
            print(f'Your final bill is: {o+1}$')
    elif p=='y':
        print(f'Your final bill is: {o+2}$')
    else:
        print(f'Your final bill is: {o}$')
else:
    if c=='y':
        if p=='y':
            print(f'Your final bill is: {l+1+3}$')
        else:
            print(f'Your final bill is: {l+1}$')
    elif p=='y':
        print(f'Your final bill is: {l+3}$')
    else:
        print(f'Your final bill is: {l}$')
        



Welcome to Python Pizza Deliveries
which size you want?s
Do you want pepperoni?y
Do you want extra cheese?y
Your final bill is: 18$


In [2]:
   if s=='m' and p=='y':
            print(f'Your final bill is: $'{20+1})
        elif s=='s' and p=='y':
            print(f'Your final bill is: $'{15+1})
        elif s=='l' and p=='y':
            print(f'Your final bill is: $'{25+1})
        elif s=='m' and p=='n':
            print(f'Your final bill is: $'{20})
        elif s=='s' and p=='n':
            print(f'Your final bill is: $'{15})
        else s=='m' and p=='n':
            print(f'Your final bill is: $'{25})
            

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [8]:
mytuple=('John','25','male')
print(mytuple[0])

mylist = ["milk", "bread", "eggs", "bananas"]
print(mylist[0])
mylist.append('chocolate')
print(mylist)
mylist.remove('milk')
print(mylist)
del mylist[0]
print(mylist)

myset={'1','2','3','4','5'}
print(myset)
myset.add('6')
print(myset)
print(len(myset))
myset.add('5')
print(myset)

mydictionary = {"name": 'john', "age": 25, "position": 'developer', "salary": 3000}
print(mydictionary)
print(mydictionary["name"])
mydictionary.pop('name')
print(mydictionary)
mydictionary['qzd']=1
print(mydictionary)

John
milk
['milk', 'bread', 'eggs', 'bananas', 'chocolate']
['bread', 'eggs', 'bananas', 'chocolate']
['eggs', 'bananas', 'chocolate']
{'2', '1', '5', '3', '4'}
{'2', '1', '6', '5', '3', '4'}
6
{'2', '1', '6', '5', '3', '4'}
{'name': 'john', 'age': 25, 'position': 'developer', 'salary': 3000}
john
{'age': 25, 'position': 'developer', 'salary': 3000}
{'age': 25, 'position': 'developer', 'salary': 3000, 'qzd': 1}


In [35]:
x=int(input('Entrez la longueur de la liste'))
l=[]


for i in range (x):
    if i==0:
        y=float(input(f'Entrez la {i+1}ère valeur de la liste '))
    else:
        y=float(input(f'Entrez la {i+1}ème valeur de la liste '))
    
    l.append(y)

for i in range (x):
    if i==0:
        print(f'la {i+1} ere valeur est',l[i])
    else:
        print(f'la {i+1} eme valeur est',l[i])


Entrez la longueur de la liste3
Entrez la 1ère valeur de la liste 1
Entrez la 2ème valeur de la liste 2
Entrez la 3ème valeur de la liste 3
la 1 ere valeur est 1.0
la 2 eme valeur est 2.0
la 3 eme valeur est 3.0


In [20]:
def remplir_tuple():
    
     x=int(input('Entrez la longueur de la liste'))
     t=()


     for i in range (x):
        if i==0:
            y=float(input(f'Entrez la {i+1}ère valeur du tuple '))
            t=t+(y,)
        else:
            y=float(input(f'Entrez la {i+1}ème valeur du tuple '))
            t=t+(y,)
     print(t)

In [21]:
remplir_tuple()

(5, 7, 7)


In [28]:
x=int(input('Entrez la longueur de la liste'))
d={}

for i in range (x):
    if i==0:
        z=input(f'Entrez le {i+1}er key ')
        y=input(f'Entrez la valeur de la {i+1}ère key ')
        d[z]=y
    else:
        z=input(f'Entrez le {i+1}eme key ')
        y=input(f'Entrez la valeur de la {i+1}ème key ')
        d[z]=y
t=list(d.keys())
r=list(d.values())
for i in range(len(d)):
    if i==0:
        print(f"le {i+1}èr key est:{t[i]}, et la {i+1}ère valeur est {r[i]}")
    else:
        print(f"le {i+1}ème key est:{t[i]}, et la {i+1}ème valeur est {r[i]}")



Entrez la longueur de la liste2
Entrez le 1er key 1
Entrez la valeur de la 1ère key 1
Entrez le 2eme key 2
Entrez la valeur de la 2ème key 2
le 1èr key est:1, et la 1ère valeur est 1
le 2ème key est:2, et la 2ème valeur est 2


In [32]:
a=input('Do you want to add, remove or view?')
l=[]

x=True
while x==True:
    if a =='add':
        b=int(input('Entrez la longueur de la liste'))
        for i in range (b):
            
            if i==0:
                
                y=float(input(f'Entrez la {i+1}ère valeur de la liste '))
            else:
                y=float(input(f'Entrez la {i+1}ème valeur de la liste '))
                l.append(y)
        x=False
        c=input('Do you want to remove or view?')
        if c=='remove':
            print(l)
            d=float(input('Choisissez le numero de la série'))
            l.remove(d)
            print(l)
        elif c=='view':
            print(l)
        
        
       
  

Do you want to add, remove or view?remove


KeyboardInterrupt: 

In [8]:
shopping_list=[]
s=0
a=True
while a==True:
    print("Menu:")
    print("1.ajouter article")
    print("2.supprimer article")
    print("3.afficher les éléments")
    print("4.Exit")
    c=int(input("choisir la commande de 1 à 4:"))
    if c==1:
        n=int(input("nombre élément à ajouter:"))
        for i in range (n):
                if i==0: 
                      E=input(f"entrer le {i+1} er élément")
                else:
                      E=input(f"entrer le {i+1} ème élément")
                shopping_list.append(E)
                print(shopping_list)
        s=s+n       
    elif c==2:
        j=input("élément à supprimer")
        shopping_list.remove(j)
        s=-1
        print(shopping_list)
    elif c==3:
        for i in range (s):
            if i==0:
                print(f"le {i+1} er élément est:",shopping_list[i])
            else:
                print(f"le {i+1}ème valeur est:",shopping_list[i])
    else:
        break

Menu:
1.ajouter article
2.supprimer article
3.afficher les éléments
4.Exit
choisir la commande de 1 à 4:1
nombre élément à ajouter:3
entrer le 1 er élément1
['1']
entrer le 2 ème élément2
['1', '2']
entrer le 3 ème élément3
['1', '2', '3']
Menu:
1.ajouter article
2.supprimer article
3.afficher les éléments
4.Exit
choisir la commande de 1 à 4:1
nombre élément à ajouter:3
entrer le 1 er élément4
['1', '2', '3', '4']
entrer le 2 ème élément5
['1', '2', '3', '4', '5']
entrer le 3 ème élément6
['1', '2', '3', '4', '5', '6']
Menu:
1.ajouter article
2.supprimer article
3.afficher les éléments
4.Exit
choisir la commande de 1 à 4:3
le 1 er élément est: 1
le 2ème valeur est: 2
le 3ème valeur est: 3
le 4ème valeur est: 4
le 5ème valeur est: 5
le 6ème valeur est: 6
Menu:
1.ajouter article
2.supprimer article
3.afficher les éléments
4.Exit
choisir la commande de 1 à 4:2
élément à supprimer2
['1', '3', '4', '5', '6']
Menu:
1.ajouter article
2.supprimer article
3.afficher les éléments
4.Exit
choisir 

KeyboardInterrupt: Interrupted by user

In [13]:
def length(liste):
    s =0 
    for i in liste:
          s+=1 #s = s+1
    return(s)
a = [5,6,7,8,9,10,11,12,'j','l','pk','jml']
print(length(a)) #4

12


In [14]:
def my_function(country="Tunisia"):
    print("I am from "+country)
my_function("Maroc")
my_function("Algeria")
my_function()

I am from Maroc
I am from Algeria
I am from Tunisia


In [29]:
def minimum(a,b):
    if a<b:
        return(a)
    else:
        return(b)

In [31]:
minimum(8,89)

8

In [36]:
def test(a,b):
    x = int(a)
    y = int(b)
    return (x-y) # write here the returned value of the function

In [37]:
test(10,7)

3

In [5]:
triple=lambda x:x*3
x=float(input('inserer un nombre:'))
r=triple(x)
print(r)

inserer un nombre:4
12.0


In [7]:
squared_numbers = map(lambda x: x*x, numbers)
print(list(squared_numbers))

NameError: name 'numbers' is not defined

In [14]:
numbers=[1, 2, 3, 4, 5] 
F=map(lambda x:x*((9/5)+ 32),numbers)
print(list(F))

[33.8, 67.6, 101.39999999999999, 135.2, 169.0]


In [ ]:
def add(a,b):
    return (a+b)
def multi(a,b):
    return (a*b)
def sub(a,b):
    return (a-b)
def div(a,b):
    return (a/b)
operations = {'+':add,'-':sub,'/':div,'*':multi}
def calculator():
    x=float(input('Entrez le premier nombre'))
    l=True
    while l==True:
        print("Les opérations disponibles sont:")
        for key in operations.keys():
            print(key)
        y=input("Entrez un opérateur")
        z=float(input("Entrez le deuxième nombre"))
        f=operations[y]
        r=f(x,z)
        print(f{x,y,'=',z})
        g=input('Voulez vous continuer?')
        if g=='yes':
            x=r
        else:
            l=False
            calculator()

            
            
            
            
    


In [ ]:
calculator()

Entrez le premier nombre2
Les opérations disponibles sont:
+
-
/
*
Entrez un opérateur+
Entrez le deuxième nombre2
4.0
Voulez vous continuer?no
good bye
Les opérations disponibles sont:
+
-
/
*


In [4]:
def __init__(self, name):
    self.name = name
def run(self):
    print(f"{self.name} is running in the game.")

In [25]:
class player:
    def __init__(self,name):
        self.name=name
        self.hp=100
    def take_damage(self,d):
        self.hp=self.hp-d
        if d>=20:
            print("le joueur",self.name,"a pris",d,"damage")
            print('il lui reste',self.hp,'de vie')
    

In [27]:
jr=player("Yassine")
jr.take_damage(40)

le joueur Yassine a pris 40 damage
il lui reste 60 de vie


In [30]:
class SuperPlayer(Player):
    def __init__(self, name, age):
        super().__init__(name, age)
        
    def fly(self):
        # code for flying in the game
        

super_player = SuperPlayer("Jack", 30)
super_player.speak()
super_player.fly()

IndentationError: expected an indented block after function definition on line 5 (3373262640.py, line 8)

In [36]:
import numpy as np
array = np.array([1, 2, 3])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

In [37]:
print(array_3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
a =np.array([0,0,0,0,1,0,0,0])
b = a.reshape(2,4)
print(b)

[[0 0 0 0]
 [1 0 0 0]]


In [42]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float16)
print(array_a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
import numpy as np

array_a = np.array([[1,2,3],[4,5,6]])
array_a

array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float16)
array_a
# Defining all the values as floats (decimals).

array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a
# Defining all the values as complex numbers.

array_a = np.array([[1,2,0],[4,5,6]], dtype = np.bool)
array_a
# Defining all the values as Booleans.

array_a = np.array([[10,2,3],[4,5,6]], dtype = np.str)
array_a
# Defining all the values as text.

In [ ]:
Basics slicing :
In this skill will explain what basics slicing is and go through a few examples :

import numpy as np
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

matrix_A[:]
## The default start and stop for slicing are the origin and the end of the array. 
## Hence, [:] includes the entire array. 

type(matrix_A[:,:])
## [:,:] -> All rows, and all columns.

matrix_A[:2]
# [:2] -> All the rows up to the 3rd one (excluding the third one).

matrix_A[:-1]
# [:-1] -> All the rows up to the last one.

matrix_A[:,1:]
# All the rows, but only the columns from the one with index 1 (second column) onwards.

matrix_A[1:,1:]
# All the rows after the first one and all the column after the first one.

In [8]:
import numpy as np

grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])


mean_grade = np.mean(grades)
median_grade = np.median(grades)
std_deviation = np.std(grades)


max_grade = np.max(grades)
min_grade = np.min(grades)


sorted_grades = np.sort(grades)


index_highest_grade = np.argmax(grades)


num_above_90 = np.sum(grades > 90)


percentage_above_90 = np.mean(grades > 90) * 100


percentage_below_75 = np.mean(grades < 75) * 100


high_performance = grades[grades > 90]


passing_grades = grades[grades > 75]


print("Mean Grade:", mean_grade)
print("Median Grade:", median_grade)
print("Standard Deviation:", std_deviation)
print("Maximum Grade:", max_grade)
print("Minimum Grade:", min_grade)
print("Sorted Grades:", sorted_grades)
print("Index of Highest Grade:", index_highest_grade)
print("Number of Students Above 90:", num_above_90)
print("Percentage of Students Above 90:", percentage_above_90)
print("Percentage of Students Below 75:", percentage_below_75)
print("High Performance Grades:", high_performance)
print("Passing Grades (Above 75):", passing_grades)


Mean Grade: 87.5
Median Grade: 88.5
Standard Deviation: 6.591661399070799
Maximum Grade: 98
Minimum Grade: 75
Sorted Grades: [75 80 83 85 88 89 90 92 95 98]
Index of Highest Grade: 7
Number of Students Above 90: 3
Percentage of Students Above 90: 30.0
Percentage of Students Below 75: 0.0
High Performance Grades: [92 95 98]
Passing Grades (Above 75): [85 90 88 92 95 80 98 89 83]
